# -*- coding: utf-8 -*-
"""resume_labels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rqSEfZimAXn3EP747kUPVL-0bg40IA1H
"""

from google.colab import files
uploaded = files.upload()

import json
with open("resume_labels.json", 'r') as f:
  json_data = json.load(f)

json_data

with open("resume_labels.jsonl", 'w') as jsonl_output:
  for entry in json_data:
    json.dump(entry, jsonl_output)
    jsonl_output.write('\n')

jsonl_file = open("resume_labels.jsonl","r")
print(jsonl_file.read())

import json
import csv

counts=0

with open("//content//resume_labels.jsonl") as f:
    for line in f:
        instance = json.loads(line)
        for entity in instance:
            counts = counts + 1
print(counts)

import json
import csv

counts = {}
with open('resume_labels.jsonl', 'r') as f:
    for line in f:
        item = json.loads(line)
        for key in item:
            if key in counts:
                counts[key] += 1
            else:
                counts[key] = 1

# Print the counts
for key, value in counts.items():
    print(f"{key}: {value}")

import json

with open('resume_labels.jsonl') as f:
    for line in f:
        data = json.loads(line)
        name = data['file_name']
        print(name)

"""some error occure in following program i don't understand"""

import json
import csv


fieldnames = ['file_name','type']


with open('output3.csv', 'w', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()

    
    with open('resume.jsonl', 'r') as jsonl_file:
        
        for line in jsonl_file:
            
            data = json.loads(line)

          
            row = {field: data[field] for field in fieldnames}

    
            writer.writerow(row)

"""And I am also not able to seperate out annotation from given json file"""

